# Generated by Django 4.2.8 on 2024-04-25 07:21

from django.db import migrations, models
import django.utils.timezone


def create_profiles(apps, schema_editor):
    CustomUser = apps.get_model('learn4all', 'CustomUser')
    Profile = apps.get_model('learn4all', 'Profile')

    for user in CustomUser.objects.all():
        Profile.objects.get_or_create(user=user)
        
class Migration(migrations.Migration):

    dependencies = [
        ('learn4all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='interview_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(create_profiles),
    ]
