# Generated by Django 4.2.8 on 2024-05-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn4all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_hrs_per_wk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_wks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LearningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_wk_result', models.JSONField()),
                ('detail_result', models.JSONField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_result', to='learn4all.profile')),
            ],
        ),
    ]
